var DB2 = {
    "spirits" :
    [{
        "nr": "1001",
        "artikelid": "190719",
        "varnummer": "10",
        "namn": "Vanlig Vodka",
        "namn2": "",
        "prisinklmoms": "195.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2006-04-01",
        "slutlev": " ",
        "varugrupp": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "Skruvkapsyl",
        "ursprung": "",
        "ursprunglandnamn": "Sverige",
        "producent": "Svensk Export Vodka AB",
        "leverantor": "Fondberg",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "1001201",
        "artikelid": "51029",
        "varnummer": "10012",
        "namn": "Dworek Vodka",
        "namn2": "",
        "prisinklmoms": "190.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2004-12-06",
        "slutlev": " ",
        "varugrupp": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Polen",
        "producent": "Tarpan Fabryka Likierow",
        "leverantor": "TIWA Trading AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "2901",
        "artikelid": "45520",
        "varnummer": "29",
        "namn": "Bols Vodka",
        "namn2": "",
        "prisinklmoms": "199.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2004-02-02",
        "slutlev": " ",
        "varugrupp": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "Skruvkapsyl",
        "ursprung": "",
        "ursprunglandnamn": "Polen",
        "producent": "Bols",
        "leverantor": "Edrington Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "301",
        "artikelid": "7",
        "varnummer": "3",
        "namn": "Explorer Vodka",
        "namn2": "",
        "prisinklmoms": "188.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "1993-10-01",
        "slutlev": " ",
        "varugrupp": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Internationellt märke",
        "producent": "Altia Sweden AB",
        "leverantor": "Altia Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "401",
        "artikelid": "11",
        "varnummer": "4",
        "namn": "Kronvodka",
        "namn2": "",
        "prisinklmoms": "219.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "1993-10-01",
        "slutlev": " ",
        "varugrupp": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Internationellt märke",
        "producent": "Altia",
        "leverantor": "Altia Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "5301",
        "artikelid": "112",
        "varnummer": "53",
        "namn": "Koskenkorva Vodka",
        "namn2": "",
        "prisinklmoms": "199.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "1992-07-01",
        "slutlev": " ",
        "varugrupp": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Finland",
        "producent": "Altia",
        "leverantor": "Altia Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "6301",
        "artikelid": "125",
        "varnummer": "63",
        "namn": "Finlandia",
        "namn2": "",
        "prisinklmoms": "235.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "1992-07-01",
        "slutlev": " ",
        "varugrupp": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "Skruvkapsyl",
        "ursprung": "",
        "ursprunglandnamn": "Finland",
        "producent": "Altia",
        "leverantor": "Philipson Söderberg AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "701",
        "artikelid": "20",
        "varnummer": "7",
        "namn": "Hallands Fläder",
        "namn2": "",
        "prisinklmoms": "239.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "1993-10-01",
        "slutlev": " ",
        "varugrupp": "Kryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Internationellt märke",
        "producent": "Altia",
        "leverantor": "Altia Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "38%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "7011502",
        "artikelid": "48781",
        "varnummer": "70115",
        "namn": "Fäbodsnaps",
        "namn2": "",
        "prisinklmoms": "269.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2004-06-01",
        "slutlev": " ",
        "varugrupp": "Kryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Internationellt märke",
        "producent": "Winzerverein Deidesheim",
        "leverantor": "Granqvist Beverage House AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "35%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "7013202",
        "artikelid": "31148",
        "varnummer": "70132",
        "namn": "Elch Blut Lingonsnaps",
        "namn2": "",
        "prisinklmoms": "156.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2001-09-01",
        "slutlev": " ",
        "varugrupp": "Kryddad sprit",
        "forpackning": "12 fl à 20 ml",
        "forslutning": "",
        "ursprung": "Skåne län, Malmö stad",
        "ursprunglandnamn": "Sverige",
        "producent": "Saturnus",
        "leverantor": "Saturnus",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "32%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "7016901",
        "artikelid": "31927",
        "varnummer": "70169",
        "namn": "Gilde",
        "namn2": "Non Plus Ultra Aquavit",
        "prisinklmoms": "429.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2001-11-01",
        "slutlev": " ",
        "varugrupp": "Kryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Norge",
        "producent": "Arcus",
        "leverantor": "Arcus Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "41.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "7022002",
        "artikelid": "722478",
        "varnummer": "70220",
        "namn": "Eriks Aquavit",
        "namn2": "",
        "prisinklmoms": "229.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-01-02",
        "slutlev": " ",
        "varugrupp": "Kryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Stockholms län, Nacka kommun",
        "ursprunglandnamn": "Sverige",
        "producent": "Liquid Services AB",
        "leverantor": "Prime Wine Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "38%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8005401",
        "artikelid": "24711",
        "varnummer": "80054",
        "namn": "LO Smith Lime-Lemon",
        "namn2": "",
        "prisinklmoms": "217.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2000-05-02",
        "slutlev": " ",
        "varugrupp": "Kryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Västra Götalands län, Götene kommun",
        "ursprunglandnamn": "Sverige",
        "producent": "J&J Nordic AB",
        "leverantor": "L O Smith AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "35%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, 
    {
        "nr": "167903",
        "artikelid": "1206",
        "varnummer": "1679",
        "namn": "Staropramen",
        "namn2": "",
        "prisinklmoms": "16.40",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "1994-02-14",
        "slutlev": " ",
        "varugrupp": "Öl, Ljus lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Tjeckien",
        "producent": "Staropramen",
        "leverantor": "Carlsberg Sverige AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    },{
        "nr": "8010002",
        "artikelid": "47893",
        "varnummer": "80100",
        "namn": "Gutevin Sparris",
        "namn2": "",
        "prisinklmoms": "246.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2004-05-01",
        "slutlev": " ",
        "varugrupp": "Kryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Gotlands län, Gotland",
        "ursprunglandnamn": "Sverige",
        "producent": "Gute Vingård AB",
        "leverantor": "Gute Vingård AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8028704",
        "artikelid": "46233",
        "varnummer": "80287",
        "namn": "Piratens Besk",
        "namn2": "",
        "prisinklmoms": "201.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2004-02-01",
        "slutlev": " ",
        "varugrupp": "Kryddad sprit",
        "forpackning": "10 fl á 50 ml",
        "forslutning": "",
        "ursprung": "Skåne län, Malmö stad",
        "ursprunglandnamn": "Sverige",
        "producent": "Saturnus",
        "leverantor": "Saturnus",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "32%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8049501",
        "artikelid": "280097",
        "varnummer": "80495",
        "namn": "Chablis Premier Cru",
        "namn2": "Labouré-Roi",
        "prisinklmoms": "199.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2007-10-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Bourgogne, Chablis, Chablis Premier Cru",
        "ursprunglandnamn": "Frankrike",
        "producent": "Labouré-Roi",
        "leverantor": "Fondberg",
        "argang": "2009",
        "provadargang": "",
        "alkoholhalt": "12.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8051601",
        "artikelid": "222802",
        "varnummer": "80516",
        "namn": "Vinha Formal",
        "namn2": "",
        "prisinklmoms": "238.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2006-10-02",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Beiras",
        "ursprunglandnamn": "Portugal",
        "producent": "Luis Pato",
        "leverantor": "Hemberga Brunn AB",
        "argang": "2008",
        "provadargang": "",
        "alkoholhalt": "13%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8056001",
        "artikelid": "221966",
        "varnummer": "80560",
        "namn": "Chapelle du Bois",
        "namn2": "Blanc",
        "prisinklmoms": "69.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2006-10-02",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Frankrike sydväst, Côtes de Gascogne I",
        "ursprunglandnamn": "Frankrike",
        "producent": "LGI",
        "leverantor": "Red & White Wine Sweden AB",
        "argang": "2012",
        "provadargang": "",
        "alkoholhalt": "11.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8059101",
        "artikelid": "222792",
        "varnummer": "80591",
        "namn": "Quinta do Ameal",
        "namn2": "Escolha",
        "prisinklmoms": "218.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2006-10-02",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Minho",
        "ursprunglandnamn": "Portugal",
        "producent": "Quinta do Ameal",
        "leverantor": "Hemberga Brunn AB",
        "argang": "2008",
        "provadargang": "",
        "alkoholhalt": "12%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8083501",
        "artikelid": "157791",
        "varnummer": "80835",
        "namn": "Terras Gauda o Rosal",
        "namn2": "",
        "prisinklmoms": "165.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2005-06-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Rías Baixas",
        "ursprunglandnamn": "Spanien",
        "producent": "Terras Gauda",
        "leverantor": "Moestue Grape Selections AB",
        "argang": "2010",
        "provadargang": "",
        "alkoholhalt": "12%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8099801",
        "artikelid": "162480",
        "varnummer": "80998",
        "namn": "Domaine Gerovassiliou",
        "namn2": "",
        "prisinklmoms": "164.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2005-07-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Makedonien, Naoussa, Epanomi",
        "ursprunglandnamn": "Grekland",
        "producent": "Domaine Gerovassiliou",
        "leverantor": "Carovin AB",
        "argang": "2009",
        "provadargang": "",
        "alkoholhalt": "12%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8100401",
        "artikelid": "162564",
        "varnummer": "81004",
        "namn": "Ojai",
        "namn2": "McGinley Vineyard Sauvignon Blanc",
        "prisinklmoms": "349.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2005-07-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Kalifornien, Central Coast, Santa Barbar",
        "ursprunglandnamn": "USA",
        "producent": "Ojai Vineyard",
        "leverantor": "Divine AB",
        "argang": "2012",
        "provadargang": "",
        "alkoholhalt": "14%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8101301",
        "artikelid": "162636",
        "varnummer": "81013",
        "namn": "Hill & Dale",
        "namn2": "Chardonnay",
        "prisinklmoms": "79.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2005-08-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Western Cape, Coastal Region, Stellenbos",
        "ursprunglandnamn": "Sydafrika",
        "producent": "Stellenzicht",
        "leverantor": "janake wine group AB",
        "argang": "2012",
        "provadargang": "",
        "alkoholhalt": "14%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8111101",
        "artikelid": "189644",
        "varnummer": "81111",
        "namn": "Morgon",
        "namn2": "",
        "prisinklmoms": "131.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2006-01-02",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Bourgogne, Beaujolais, Beaujolais Cru, M",
        "ursprunglandnamn": "Frankrike",
        "producent": "Joseph Drouhin",
        "leverantor": "Hjo Grosshandel AB",
        "argang": "2010",
        "provadargang": "",
        "alkoholhalt": "13%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8114901",
        "artikelid": "165306",
        "varnummer": "81149",
        "namn": "Raimat",
        "namn2": "Cabernet Sauvignon Vallcorba Reserva",
        "prisinklmoms": "189.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2005-08-01",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Costers del Segre",
        "ursprunglandnamn": "Spanien",
        "producent": "Raimat",
        "leverantor": "Bibendum",
        "argang": "2009",
        "provadargang": "",
        "alkoholhalt": "13.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8118901",
        "artikelid": "166751",
        "varnummer": "81189",
        "namn": "Barbera d'Asti",
        "namn2": "Superiore Vigna delle Rose",
        "prisinklmoms": "180.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2005-08-01",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Piemonte, Barbera d'Asti",
        "ursprunglandnamn": "Italien",
        "producent": "Franco Mondo",
        "leverantor": "Wester Wine & Food AB",
        "argang": "2008",
        "provadargang": "",
        "alkoholhalt": "14.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8119101",
        "artikelid": "744406",
        "varnummer": "81191",
        "namn": "Dolcetto Trevigne",
        "namn2": "",
        "prisinklmoms": "93.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-01",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Piemonte, Monferrato, Monferrato Dolcett",
        "ursprunglandnamn": "Italien",
        "producent": "Franco Mondo",
        "leverantor": "Wester Wine & Food AB",
        "argang": "2011",
        "provadargang": "",
        "alkoholhalt": "12.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8120401",
        "artikelid": "279463",
        "varnummer": "81204",
        "namn": "Riscal 1860",
        "namn2": "Tempranillo",
        "prisinklmoms": "88.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2007-10-01",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Castilla y León",
        "ursprunglandnamn": "Spanien",
        "producent": "Vinos Blancos de Castilla",
        "leverantor": "Nigab",
        "argang": "2011",
        "provadargang": "",
        "alkoholhalt": "13.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8122901",
        "artikelid": "189785",
        "varnummer": "81229",
        "namn": "Heitz Napa Valley",
        "namn2": "Cabernet Sauvignon",
        "prisinklmoms": "471.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2006-01-02",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Kalifornien, North Coast, Napa Valley",
        "ursprunglandnamn": "USA",
        "producent": "Heitz Wine Cellars",
        "leverantor": "Hjo Grosshandel AB",
        "argang": "2006",
        "provadargang": "",
        "alkoholhalt": "14.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8125101",
        "artikelid": "190213",
        "varnummer": "81251",
        "namn": "Nero d'Avola",
        "namn2": "",
        "prisinklmoms": "79.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2006-01-02",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Sicilien",
        "ursprunglandnamn": "Italien",
        "producent": "Cusumano",
        "leverantor": "Prime Wine Sweden AB",
        "argang": "2012",
        "provadargang": "",
        "alkoholhalt": "13.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8125401",
        "artikelid": "193051",
        "varnummer": "81254",
        "namn": "Poggio Teo",
        "namn2": "Valiano",
        "prisinklmoms": "169.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2006-02-01",
        "slutlev": " ",
        "varugrupp": "Rött vin",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Toscana, Chianti, Chianti Classico",
        "ursprunglandnamn": "Italien",
        "producent": "Gestioni Piccini",
        "leverantor": "Enjoy Wine & Spirits AB",
        "argang": "2006",
        "provadargang": "",
        "alkoholhalt": "13.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8143601",
        "artikelid": "27072",
        "varnummer": "81436",
        "namn": "Weltenburger",
        "namn2": "Anno 1050",
        "prisinklmoms": "24.50",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2000-12-01",
        "slutlev": " ",
        "varugrupp": "Öl, Ljus lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Tyskland",
        "producent": "Weltenburg Klosterbrauerei",
        "leverantor": "Österlenbryggarna AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "5.3%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8149901",
        "artikelid": "53469",
        "varnummer": "81499",
        "namn": "Heineken",
        "namn2": "",
        "prisinklmoms": "17.90",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2005-04-01",
        "slutlev": " ",
        "varugrupp": "Öl, Ljus lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Internationellt märke",
        "producent": "Spendrups",
        "leverantor": "Spendrups Bryggeri AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8159401",
        "artikelid": "21717",
        "varnummer": "81594",
        "namn": "Ahlafors",
        "namn2": "Ljusa",
        "prisinklmoms": "23.60",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2000-01-01",
        "slutlev": " ",
        "varugrupp": "Öl, Ljus lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Västra Götalands län, Ale kommun",
        "ursprunglandnamn": "Sverige",
        "producent": "Ahlafors Bryggerier AB",
        "leverantor": "Ahlafors Bryggerier AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "5%",
        "modul": "",
        "sortiment": "TSLS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8358303",
        "artikelid": "261020",
        "varnummer": "83583",
        "namn": "Three Hearts",
        "namn2": "Premium Lager",
        "prisinklmoms": "11.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2007-06-01",
        "slutlev": " ",
        "varugrupp": "Öl, Ljus lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Hallands län, Halmstads kommun",
        "ursprunglandnamn": "Sverige",
        "producent": "Krönleins",
        "leverantor": "Krönleins",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "5.2%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8802303",
        "artikelid": "400537",
        "varnummer": "88023",
        "namn": "Tiger Beer",
        "namn2": "",
        "prisinklmoms": "16.20",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2009-07-01",
        "slutlev": " ",
        "varugrupp": "Öl, Ljus lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Singapore",
        "producent": "Asia Pacific Breweries",
        "leverantor": "Spendrups Bryggeri AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "4.6%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8805901",
        "artikelid": "551286",
        "varnummer": "88059",
        "namn": "Svaneke",
        "namn2": "Pilsner",
        "prisinklmoms": "25.90",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2011-01-03",
        "slutlev": " ",
        "varugrupp": "Öl, Ljus lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Danmark",
        "producent": "Svaneke Bryghus",
        "leverantor": "Brewery International Sweden A",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "4.6%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8808103",
        "artikelid": "397514",
        "varnummer": "88081",
        "namn": "Sarajevsko",
        "namn2": "",
        "prisinklmoms": "13.50",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2009-08-01",
        "slutlev": " ",
        "varugrupp": "Öl, Ljus lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Bosnien-Hercegovina",
        "producent": "Sarajevska Pivara",
        "leverantor": "Plivit Trade AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "4.9%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8811801",
        "artikelid": "543706",
        "varnummer": "88118",
        "namn": "Falcon Strong Brew",
        "namn2": "",
        "prisinklmoms": "15.90",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2010-12-01",
        "slutlev": " ",
        "varugrupp": "Öl, Ljus lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Hallands län, Falkenbergs kommun",
        "ursprunglandnamn": "Sverige",
        "producent": "Carlsberg Sverige AB",
        "leverantor": "Carlsberg Sverige AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "7.2%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8826701",
        "artikelid": "609772",
        "varnummer": "88267",
        "namn": "Zeunerts Julöl",
        "namn2": "",
        "prisinklmoms": "17.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2011-11-01",
        "slutlev": " ",
        "varugrupp": "Öl, Mörk lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Västernorrlands län, Sollefteå kommun",
        "ursprunglandnamn": "Sverige",
        "producent": "Kopparbergs/Sofiero Bryggeri",
        "leverantor": "Kopparbergs/Sofiero Bryggeri",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "5.1%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8850103",
        "artikelid": "580163",
        "varnummer": "88501",
        "namn": "Grebbestads",
        "namn2": "Mörka",
        "prisinklmoms": "18.20",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2011-05-02",
        "slutlev": " ",
        "varugrupp": "Öl, Mörk lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Västra Götalands län, Tanums kommun",
        "ursprunglandnamn": "Sverige",
        "producent": "Grebbestad Bryggeri",
        "leverantor": "Grebbestad Bryggeri AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "4.9%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8858701",
        "artikelid": "540299",
        "varnummer": "88587",
        "namn": "Pinkus Jubilate",
        "namn2": "",
        "prisinklmoms": "34.50",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2010-12-01",
        "slutlev": " ",
        "varugrupp": "Öl, Mörk lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Tyskland",
        "producent": "Brauerei Pinkus Müller",
        "leverantor": "Skandinaviska Dryckeshuset AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "5.5%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "1",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8900003",
        "artikelid": "578470",
        "varnummer": "89000",
        "namn": "Taybeh Beer",
        "namn2": "Dark",
        "prisinklmoms": "28.10",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2011-05-02",
        "slutlev": " ",
        "varugrupp": "Öl, Mörk lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "De Palestinska Områdena",
        "ursprunglandnamn": "Övriga ursprung",
        "producent": "Taybeh",
        "leverantor": "First Signs of Water AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "6%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8904401",
        "artikelid": "634861",
        "varnummer": "89044",
        "namn": "Krombacher",
        "namn2": "Dark",
        "prisinklmoms": "20.20",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-01-02",
        "slutlev": " ",
        "varugrupp": "Öl, Mörk lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Tyskland",
        "producent": "Krombacher Brauerei",
        "leverantor": "Haugen-Gruppen AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "4.3%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8916903",
        "artikelid": "650525",
        "varnummer": "89169",
        "namn": "Gold Star",
        "namn2": "Dark Lager",
        "prisinklmoms": "38.90",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-03-01",
        "slutlev": " ",
        "varugrupp": "Öl, Mörk lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Israel",
        "producent": "Tembo Beer Industries",
        "leverantor": "World Beer Trading KB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "4.9%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8923601",
        "artikelid": "647238",
        "varnummer": "89236",
        "namn": "Konrad",
        "namn2": "Mörk Lager",
        "prisinklmoms": "18.40",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-03-01",
        "slutlev": " ",
        "varugrupp": "Öl, Mörk lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Tjeckien",
        "producent": "Hols",
        "leverantor": "Bibendum",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "4.3%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }, {
        "nr": "8928203",
        "artikelid": "837948",
        "varnummer": "89282",
        "namn": "Premiumöl Extraordinär",
        "namn2": "",
        "prisinklmoms": "34.50",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-04-01",
        "slutlev": " ",
        "varugrupp": "Öl, Mörk lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skåne län, Båstads kommun",
        "ursprunglandnamn": "Sverige",
        "producent": "Båstad Öl HB",
        "leverantor": "Aktiebolaget Grundstenen 14070",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "7.2%",
        "modul": "",
        "sortiment": "TSLS",
        "ekologisk": "0",
        "koscher": "0",
        "stock": "20",
        "hidden": "0"
    }]
};
